server:
  port: 8081

spring:
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

logging:
  level:
    com.ahamo.dummy.demo2.gateway: DEBUG
