name: E2E Integration Testing

on:
  workflow_call:
    inputs:
      ENV:
        required: true
        type: string

jobs:
  e2e-test-execution:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
        test-suite: [user-flows, api-integration, cross-service]
    steps:
      - name: Checkout E2E Repository
        uses: actions/checkout@v4
        with:
          path: e2e

      - name: Checkout Frontend Repository
        uses: actions/checkout@v4
        with:
          repository: satoshi-watanabe-0001/ahamo-dummy-demo2-frontend-workspace
          path: e2e/repos/ahamo-dummy-demo2-frontend-workspace
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout API Gateway Repository
        uses: actions/checkout@v4
        with:
          repository: satoshi-watanabe-0001/ahamo-dummy-demo2-api-gateway-service
          path: e2e/repos/ahamo-dummy-demo2-api-gateway-service
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Auth Service Repository
        uses: actions/checkout@v4
        with:
          repository: satoshi-watanabe-0001/-satoshi-watanabe-0001-ahamo-dummy-demo2-auth-service
          path: e2e/repos/-satoshi-watanabe-0001-ahamo-dummy-demo2-auth-service
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Start E2E Environment
        working-directory: e2e
        run: |
          echo "Building containers from source repositories..."
          docker-compose -f docker-compose.e2e.yml build
          echo "Starting E2E environment..."
          docker-compose -f docker-compose.e2e.yml up -d
          sleep 60

      - name: Health Check
        working-directory: e2e
        run: |
          curl -f http://localhost:3000/health || echo "Frontend health check failed"
          curl -f http://localhost:8080/actuator/health || echo "Auth service health check failed"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install E2E Dependencies
        working-directory: e2e
        run: npm ci

      - name: Run E2E Tests
        working-directory: e2e
        run: |
          npx playwright test tests/${{ matrix.test-suite }} \
            --project=${{ matrix.browser }} \
            --reporter=json \
            --output-file=results-${{ matrix.browser }}-${{ matrix.test-suite }}.json

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-results-${{ matrix.browser }}-${{ matrix.test-suite }}
          path: e2e/results-${{ matrix.browser }}-${{ matrix.test-suite }}.json

      - name: Cleanup Environment
        if: always()
        working-directory: e2e
        run: docker-compose -f docker-compose.e2e.yml down -v
