name: E2E Integration Testing

on:
  workflow_call:
    inputs:
      ENV:
        required: true
        type: string

jobs:
  e2e-test-execution:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
        test-suite: [user-flows, api-integration, cross-service]
    steps:
      - name: Checkout E2E Repository
        uses: actions/checkout@v4

      - name: Start E2E Environment
        run: |
          docker-compose -f docker-compose.e2e.yml up -d
          sleep 60

      - name: Health Check
        run: |
          curl -f http://localhost:3000/health || exit 1
          curl -f http://localhost:8080/actuator/health || exit 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run E2E Tests
        run: |
          npx playwright test tests/${{ matrix.test-suite }} \
            --project=${{ matrix.browser }} \
            --reporter=json \
            --output-file=results-${{ matrix.browser }}-${{ matrix.test-suite }}.json

      - name: Cleanup Environment
        if: always()
        run: docker-compose -f docker-compose.e2e.yml down -v
